FROM python:3.9

# rodar um comando para instalar os módulos faltando (mysql, kafka)

RUN apt-get update && apt-get upgrade -y && apt-get install nano -y
    
COPY requirements.txt .
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Copiar o script python para dentro do container
COPY ./consumer.py .



# Executar via CMD os script python
ENTRYPOINT [ "/bin/bash" ]

# docker build -t kafka_consumer --file Dockerfile-consumer .
# docker run --rm -it --name kafka_consumer --network single-node_default kafka_consumer
# Network single-noe_default:
# - MySQL
# - Zookeper
# - Kafka
# - Este container
# - Producer 